<?php
/**
 * @package wp-fix-urls
 * @version 1
 */
/*
Plugin Name: Fix URLs
Plugin URI:
Description: Fix URLs generated by WordPress to change http:// to the schemaless version.
Author: Sean Kelly
Version: 1
Author URI:
*/

namespace org\wgom;

/*
 * Replace all URLs beginning with http:// to the schemaless version.
 */
function fix_urls($url, $postid) {
	if (stripos($url, 'http:') === 0) {
		return substr($url, 5);
	}
}

\add_filter('wp_get_attachment_url', 'org\\wgom\\fix_urls', '', 2);
